name: Extract Packages

on:
  push:
    branches:
      - devel
    paths:
      - 'DESCRIPTION'
      - '**.yml'

permissions: write-all

jobs:
  extract_packages:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install R dependencies
        run: Rscript -e 'install.packages("stringi")' # Install any packages your script needs

      - name: Run extract_packages script
        run: Rscript extract_packages.R

      - name: Commit and push changes
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add oma_packages.csv
          git commit -m "Update oma_packages.csv" -a || echo "No changes to commit"
          git push origin || echo "No changes to commit"
